const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const questions=[
{q:"Chỉ việc làm không đến nơi đến chốn, bỏ dở giữa chừng.",hint:"Có hình ảnh con voi và đuôi chuột.",a:"Đầu voi đuôi chuột",c:["Đầu voi đuôi chuột","Cưỡi ngựa xem hoa","Nước đổ lá khoai","Há miệng chờ sung"],ex:"Thành ngữ này nói về việc khởi đầu to tát nhưng kết thúc nhỏ bé, kém chất lượng."},
{q:"Khuyên phải nhớ ơn người đã giúp mình.",hint:"Liên quan đến quả và người trồng cây.",a:"Ăn quả nhớ kẻ trồng cây",c:["Ăn quả nhớ kẻ trồng cây","Có công mài sắt có ngày nên kim","Uống nước nhớ nguồn","Lá lành đùm lá rách"],ex:"Câu này nhấn mạnh lòng biết ơn với người tạo ra thành quả."},
{q:"Làm việc qua loa, chỉ nhìn bề ngoài.",hint:"Có hình ảnh đi xem hoa khi đang cưỡi ngựa.",a:"Cưỡi ngựa xem hoa",c:["Cưỡi ngựa xem hoa","Đẽo cày giữa đường","Thả con săn sắt bắt con cá rô","Đứng núi này trông núi nọ"],ex:"Ý nói quan sát hời hợt, không tìm hiểu kỹ."},
{q:"Người thiếu hiểu biết nhưng lại hay khoe khoang.",hint:"Gắn với chiếc thùng và tiếng kêu.",a:"Thùng rỗng kêu to",c:["Thùng rỗng kêu to","Ếch ngồi đáy giếng","Múa rìu qua mắt thợ","Nói có sách mách có chứng"],ex:"Thùng rỗng kêu to ví người ít thực chất nhưng hay làm ồn."},
{q:"Ở hoàn cảnh khó khăn mới biết ai thật lòng.",hint:"Lửa dùng để thử một kim loại quý.",a:"Lửa thử vàng gian nan thử sức",c:["Lửa thử vàng gian nan thử sức","Có chí thì nên","Thất bại là mẹ thành công","Gần mực thì đen gần đèn thì sáng"],ex:"Khó khăn là phép thử cho năng lực và bản lĩnh."},
{q:"Một việc rất hiếm khi xảy ra.",hint:"Liên quan đến trăng và ngày cuối tháng.",a:"Năm thì mười họa",c:["Năm thì mười họa","Một nắng hai sương","Ba chìm bảy nổi","Chín người mười ý"],ex:"Dùng để chỉ tần suất rất thưa, hiếm gặp."},
{q:"Không biết lượng sức, làm chuyện vượt quá khả năng.",hint:"Một dụng cụ thợ mộc bị làm ngay giữa đường.",a:"Đẽo cày giữa đường",c:["Đẽo cày giữa đường","Múa rìu qua mắt thợ","Đứng núi này trông núi nọ","Lấy trứng chọi đá"],ex:"Còn chỉ người thiếu chính kiến, nghe ai cũng sửa theo."},
{q:"Tích góp từng chút một, lâu ngày sẽ thành kết quả lớn.",hint:"Liên quan đến con kiến và cái tổ.",a:"Kiến tha lâu đầy tổ",c:["Kiến tha lâu đầy tổ","Một con sâu làm rầu nồi canh","Tức nước vỡ bờ","Sai một ly đi một dặm"],ex:"Đáp án đúng theo nghĩa tích lũy từng chút một để thành kết quả lớn."},
{q:"Người ngoài cuộc thường tỉnh táo hơn người trong cuộc.",hint:"Liên quan đến cờ và nước đi.",a:"Trong cuộc u mê ngoài cuộc sáng",c:["Trong cuộc u mê ngoài cuộc sáng","Cờ đến tay ai người ấy phất","Sai một ly đi một dặm","Chưa đỗ ông nghè đã đe hàng tổng"],ex:"Người ngoài ít bị cảm xúc chi phối nên nhìn rõ hơn."},
{q:"Không thể che giấu mãi một sự thật rõ ràng.",hint:"Cây kim và cái bọc.",a:"Cái kim trong bọc lâu ngày cũng lòi ra",c:["Cái kim trong bọc lâu ngày cũng lòi ra","Giấu đầu hở đuôi","Có tật giật mình","Cháy nhà ra mặt chuột"],ex:"Sự thật dù bị che kỹ vẫn có lúc lộ ra."},
{q:"Đoàn kết, giúp người khó khăn hơn mình.",hint:"Lá tốt che chở lá bị rách.",a:"Lá lành đùm lá rách",c:["Lá lành đùm lá rách","Một cây làm chẳng nên non","Bầu ơi thương lấy bí cùng","Chị ngã em nâng"],ex:"Nói về sự đùm bọc, tương trợ trong cộng đồng."},
{q:"Tham lợi nhỏ mà bỏ lỡ lợi lớn.",hint:"Con săn sắt và cá rô.",a:"Thả con săn sắt bắt con cá rô",c:["Thả con săn sắt bắt con cá rô","Được voi đòi tiên","Tham bát bỏ mâm","Mất bò mới lo làm chuồng"],ex:"Ý là bỏ ra cái nhỏ để nhắm tới cái lớn hơn."}
];
const state={deck:[],i:0,score:0,correct:0,streak:0};
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}function show(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id))}function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}function best(){ $("#bestScore").textContent=Number(localStorage.getItem("doan-thanh-ngu-best")||0)}
function start(){state.deck=shuffle(questions).slice(0,10);state.i=0;state.score=0;state.correct=0;state.streak=0;show("gameScreen");render()}
function render(){const q=state.deck[state.i];$("#roundText").textContent=`Câu ${state.i+1}/${state.deck.length}`;$("#scoreText").textContent=state.score;$("#progressBar").style.width=`${((state.i+1)/state.deck.length)*100}%`;$("#categoryText").textContent="Gợi ý nghĩa";$("#questionText").textContent=q.q;$("#hintText").textContent=q.hint;$("#answerGrid").innerHTML=shuffle(q.c).map(c=>`<button class="answer-button" data-a="${c}">${c}</button>`).join("");$$(".answer-button").forEach(b=>b.onclick=()=>answer(b,q))}
function answer(btn,q){const ok=btn.dataset.a===q.a;$$(".answer-button").forEach(b=>{b.disabled=true;if(b.dataset.a===q.a)b.classList.add("correct")});if(!ok)btn.classList.add("wrong");if(ok){state.score+=100+state.streak*25;state.correct++;state.streak++;$("#feedbackIcon").textContent="✨";$("#feedbackLabel").textContent="Chính xác";$("#feedbackTitle").textContent=q.a;$("#feedbackText").textContent=q.ex}else{state.streak=0;$("#feedbackIcon").textContent="📌";$("#feedbackLabel").textContent="Chưa đúng";$("#feedbackTitle").textContent=q.a;$("#feedbackText").textContent=q.ex}state.i++;setTimeout(()=>show("feedbackScreen"),400)}
function next(){if(state.i>=state.deck.length)return finish();show("gameScreen");render()}function finish(){const old=Number(localStorage.getItem("doan-thanh-ngu-best")||0);if(state.score>old)localStorage.setItem("doan-thanh-ngu-best",state.score);best();$("#resultTitle").textContent=state.correct>=9?"Cao thủ thành ngữ!":state.correct>=7?"Vốn tiếng Việt rất ổn!":state.correct>=5?"Sắp thuộc bài rồi!":"Một lượt nữa sẽ lên tay!";$("#finalScore").textContent=state.score;$("#finalCorrect").textContent=`${state.correct}/${state.deck.length} câu đúng`;if(typeof recordGameScore==='function'){recordGameScore('Đoán Thành Ngữ',state.score,'📜');}show("resultScreen")}
async function share(text,msg){const url=location.origin+location.pathname;if(navigator.share){try{await navigator.share({title:"Đoán Thành Ngữ",text,url});return}catch(e){if(e.name==="AbortError")return}}await navigator.clipboard.writeText(`${text} ${url}`);toast(msg)}
$("#startButton").onclick=start;$("#replayButton").onclick=start;$("#nextButton").onclick=next;$("#shareGameButton").onclick=()=>share("Thử chơi Đoán Thành Ngữ: đọc gợi ý và chọn đúng thành ngữ Việt Nam.","Đã sao chép link game");$("#welcomeShareButton").onclick=$("#shareGameButton").onclick;$("#shareResultButton").onclick=()=>share(`Tôi được ${state.score} điểm trong Đoán Thành Ngữ, đúng ${state.correct}/${state.deck.length} câu.`, "Đã sao chép lời thách");best();
