const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const baseWords=[
["PLANET","Hành tinh trong vũ trụ"],["MEMORY","Khả năng ghi nhớ"],["BRIDGE","Cây cầu, sự kết nối"],["FOREST","Khu rừng"],["BRAVE","Dũng cảm"],["PUZZLE","Câu đố, trò giải đố"],["ENERGY","Năng lượng"],["GARDEN","Khu vườn"],["TRAVEL","Du lịch"],["WONDER","Điều kỳ diệu hoặc sự tò mò"],["BALANCE","Sự cân bằng"],["FUTURE","Tương lai"],["SILENT","Yên lặng"],["FOCUS","Tập trung"],["CREATE","Tạo ra"]
];
const words=[...new Map([...baseWords,...(window.GAME_WORD_BANK_1000||[]).map(w=>[w,`Từ tiếng Anh có ${w.length} chữ cái`])].map(item=>[item[0],item])).values()].slice(0,1000);
const letters="ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");const state={deck:[],i:0,score:0,correct:0,word:"",hint:"",guessed:new Set(),wrong:0};
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}function show(id){$$(".screen").forEach(x=>{const active=x.id===id;x.classList.toggle("active",active);x.hidden=!active;x.setAttribute("aria-hidden",String(!active))})}function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}function best(){$("#bestScore").textContent=Number(localStorage.getItem("hangman-best")||0)}
function start(){state.deck=shuffle(words).slice(0,8);state.i=0;state.score=0;state.correct=0;show("gameScreen");loadWord()}function loadWord(){[state.word,state.hint]=state.deck[state.i];state.guessed=new Set();state.wrong=0;render()}
function render(){const masked=state.word.split("").map(ch=>state.guessed.has(ch)?ch:"_").join(" ");$("#roundText").textContent=`Từ ${state.i+1}/${state.deck.length}`;$("#scoreText").textContent=state.score;$("#progressBar").style.width=`${((state.i+1)/state.deck.length)*100}%`;$("#maskedWord").textContent=masked;$("#hintText").textContent=state.hint;$("#wrongText").textContent=`Sai: ${state.wrong}/6`;$("#face").textContent=["🙂","🙂","😐","😟","😰","😵","💀"][state.wrong];$("#keyboard").innerHTML=letters.map(l=>`<button class="key ${state.guessed.has(l)&&state.word.includes(l)?"good":""} ${state.guessed.has(l)&&!state.word.includes(l)?"bad":""}" ${state.guessed.has(l)?"disabled":""} data-l="${l}">${l}</button>`).join("");$$(".key").forEach(b=>b.onclick=()=>guess(b.dataset.l))}
function guess(l){state.guessed.add(l);if(!state.word.includes(l))state.wrong++;const won=state.word.split("").every(ch=>state.guessed.has(ch));if(won){state.score+=120+Math.max(0,6-state.wrong)*20;state.correct++;return feedback(true)}if(state.wrong>=6)return feedback(false);render()}
function feedback(ok){$("#feedbackIcon").textContent=ok?"✅":"💀";$("#feedbackLabel").textContent=ok?"Đoán đúng":"Hết lượt";$("#feedbackTitle").textContent=state.word;$("#feedbackText").textContent=ok?"Bạn giữ được từ này trước khi hết lượt sai.":`Gợi ý là: ${state.hint}`;state.i++;setTimeout(()=>show("feedbackScreen"),350)}
function next(){if(state.i>=state.deck.length)return finish();show("gameScreen");loadWord()}function finish(){const old=Number(localStorage.getItem("hangman-best")||0);if(state.score>old)localStorage.setItem("hangman-best",state.score);best();$("#resultTitle").textContent=state.correct>=7?"Đoán chữ quá bén!":state.correct>=5?"Từ vựng khá chắc!":"Một lượt nữa sẽ nhớ hơn!";$("#finalScore").textContent=state.score;$("#finalCorrect").textContent=`${state.correct}/${state.deck.length} từ đúng`;if(typeof recordGameScore==='function'){recordGameScore('Hangman',state.score,'✍️');}show("resultScreen")}
async function share(text,msg){const url=location.origin+location.pathname;if(navigator.share){try{await navigator.share({title:"Hangman",text,url});return}catch(e){if(e.name==="AbortError")return}}await navigator.clipboard.writeText(`${text} ${url}`);toast(msg)}
$("#startButton").onclick=start;$("#replayButton").onclick=start;$("#nextButton").onclick=next;$("#shareGameButton").onclick=()=>share("Thử chơi Hangman: đoán từ tiếng Anh trước khi hết lượt sai.","Đã sao chép link game");$("#welcomeShareButton").onclick=$("#shareGameButton").onclick;$("#shareResultButton").onclick=()=>share(`Tôi được ${state.score} điểm trong Hangman, đoán đúng ${state.correct}/${state.deck.length} từ.`, "Đã sao chép lời thách");best();
