const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const baseAnswers=["APPLE","BRAVE","BRAIN","BREAD","CHAIR","CLOUD","DREAM","EARTH","FAITH","FOCUS","FRESH","GHOST","GRAPE","GREEN","HEART","HOUSE","LIGHT","MAGIC","MONEY","MUSIC","NIGHT","OCEAN","PEACE","PLANT","POWER","QUICK","RIVER","SHARE","SMILE","SMART","STONE","STORY","TRAIN","TRUST","WATER","WORLD","YOUNG"];
function buildAnswers(){const words=(window.GAME_WORD_BANK_1000||[]).filter(w=>/^[A-Z]+$/.test(w));const picked=[];const add=w=>{if(w.length===5&&!picked.includes(w))picked.push(w)};baseAnswers.forEach(add);words.forEach(add);words.forEach(w=>add(w.slice(0,5)));words.forEach(w=>add(w.slice(-5)));for(const w of words){if(picked.length>=1000)break;add((w+"S").slice(0,5))}const vowels="AEIOU", consonants="BCDFGHJKLMNPQRSTVWXYZ";let i=0;while(picked.length<1000){const w=consonants[i%consonants.length]+vowels[Math.floor(i/21)%5]+consonants[Math.floor(i/105)%consonants.length]+vowels[Math.floor(i/2205)%5]+consonants[Math.floor(i/11025)%consonants.length];add(w);i++}return picked.slice(0,1000)}
const answers=buildAnswers();
let state={answer:"",row:0,col:0,guesses:Array.from({length:6},()=>Array(5).fill("")),done:false,score:0};
const letters="QWERTYUIOPASDFGHJKLZXCVBNM";
function show(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id))}function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}function best(){$("#bestScore").textContent=Number(localStorage.getItem("wordle-best")||0)}function pick(){return answers[Math.floor(Math.random()*answers.length)]}
function start(){state={answer:pick(),row:0,col:0,guesses:Array.from({length:6},()=>Array(5).fill("")),done:false,score:0};show("gameScreen");render()}
function render(){let html="";for(let r=0;r<6;r++){html+=`<div class="word-row">`;for(let c=0;c<5;c++)html+=`<div class="tile" id="t-${r}-${c}">${state.guesses[r][c]}</div>`;html+=`</div>`}$("#board").innerHTML=html;for(let r=0;r<state.row;r++)paintRow(r);$("#keyboard").innerHTML=[..."QWERTYUIOP","ASDFGHJKL","ZXCVBNM"].map(row=>row.split("").map(l=>`<button class="key" data-k="${l}">${l}</button>`).join("")).join("")+`<button class="key wide" data-k="ENTER">ENTER</button><button class="key wide" data-k="BACK">⌫</button>`;$$(".key").forEach(b=>b.onclick=()=>press(b.dataset.k));paintKeys();$("#turnText").textContent=`Lượt ${Math.min(state.row+1,6)}/6`;$("#scoreText").textContent=state.score}
function press(k){if(state.done)return;if(k==="BACK"){if(state.col>0)state.guesses[state.row][--state.col]="";return render()}if(k==="ENTER")return submit();if(state.col<5&&/^[A-Z]$/.test(k)){state.guesses[state.row][state.col++]=k;render()}}
function submit(){if(state.col<5)return toast("Cần đủ 5 chữ");const guess=state.guesses[state.row].join("");paintRow(state.row);if(guess===state.answer)return end(true);state.row++;state.col=0;if(state.row>=6)return end(false);render()}
function rowStatus(guess){const ans=state.answer.split(""), res=Array(5).fill("absent");for(let i=0;i<5;i++)if(guess[i]===ans[i]){res[i]="correct";ans[i]=null}for(let i=0;i<5;i++)if(res[i]!=="correct"){const j=ans.indexOf(guess[i]);if(j>=0){res[i]="present";ans[j]=null}}return res}
function paintRow(r){const guess=state.guesses[r].join("");if(guess.length<5)return;rowStatus(guess).forEach((s,i)=>$(`#t-${r}-${i}`)?.classList.add(s))}
function paintKeys(){const rank={absent:1,present:2,correct:3};const seen={};for(let r=0;r<state.row;r++){const g=state.guesses[r].join("");rowStatus(g).forEach((s,i)=>{const ch=g[i];if(!seen[ch]||rank[s]>rank[seen[ch]])seen[ch]=s})}$$(".key").forEach(b=>{const s=seen[b.dataset.k];if(s)b.classList.add(s)})}
function end(win){state.done=true;state.score=win?700-state.row*80:100;const old=Number(localStorage.getItem("wordle-best")||0);if(state.score>old)localStorage.setItem("wordle-best",state.score);best();$("#resultIcon").textContent=win?"🏆":"🧩";$("#resultTitle").textContent=win?`Đúng trong ${state.row+1} lượt!`:"Chưa ra từ này";$("#answerText").textContent=state.answer;$("#scoreLine").textContent=`${state.score} điểm`;show("resultScreen")}
async function share(text,msg){const url=location.origin+location.pathname;if(navigator.share){try{await navigator.share({title:"Wordle",text,url});return}catch(e){if(e.name==="AbortError")return}}await navigator.clipboard.writeText(`${text} ${url}`);toast(msg)}
$("#startButton").onclick=start;$("#replayButton").onclick=start;$("#newButton").onclick=start;$("#shareGameButton").onclick=()=>share("Thử chơi Wordle: đoán từ tiếng Anh 5 chữ cái trong 6 lượt.","Đã sao chép link game");$("#welcomeShareButton").onclick=$("#shareGameButton").onclick;$("#shareResultButton").onclick=()=>share(`Tôi vừa chơi Wordle được ${state.score} điểm. Đáp án là ${state.answer}.`, "Đã sao chép lời thách");best();
