const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const mode = document.body.dataset.mode;
const config = {
  picture:{name:"Icon Vocabulary",icon:"🖼️",rounds:12}, emoji:{name:"Emoji Vocabulary",icon:"😊",rounds:12}, grammar:{name:"Grammar Quiz",icon:"📝",rounds:12},
  sentence:{name:"Sentence Builder",icon:"🔧",rounds:10}, listening:{name:"Listening",icon:"🔊",rounds:12}, reading:{name:"Reading",icon:"📚",rounds:10},
  typing:{name:"Typing",icon:"⌨️",rounds:12}, daily:{name:"Daily Challenge",icon:"🏆",rounds:10}, speed:{name:"60s Challenge",icon:"🎯",rounds:999}
}[mode];
let vocabulary = [], timerId = null, nextTimerId = null;
const state = {deck:[],index:0,score:0,correct:0,combo:0,answered:false,selected:[],seconds:60,finished:false};
const RECENT_KEY = `english-${mode}-recent`;
const BEST_KEY = `english-${mode}-best`;
const DAILY_KEY = 'english-daily-progress';
const shuffle = items => [...items].sort(() => Math.random() - .5);
const itemIndex = (item,salt='') => [...`${item.word}${salt}`].reduce((sum,ch)=>sum+ch.charCodeAt(0),0);
function loadList(key){try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return[]}}
function saveList(key,list){localStorage.setItem(key,JSON.stringify([...new Set(list)]))}
function loadDaily(){try{return JSON.parse(localStorage.getItem(DAILY_KEY)||'{"last":"","streak":0,"best":0}')}catch{return{last:'',streak:0,best:0}}}
function recordDaily(){const progress=loadDaily();const today=localDay();if(progress.last!==today){progress.streak=progress.last===localDay(-1)?progress.streak+1:1;progress.last=today;progress.best=Math.max(progress.best||0,progress.streak);localStorage.setItem(DAILY_KEY,JSON.stringify(progress))}return progress}
function show(id){$$('.screen').forEach(el=>{const active=el.id===id;el.classList.toggle('active',active);el.hidden=!active;el.setAttribute('aria-hidden',String(!active))})}
function setupSharedLayout(){const actions=$('.header-actions');const status=$('#timerText');if(mode==='speed')status.textContent='60s';else{status.classList.remove('timer');status.innerHTML=`Kỷ lục <strong id="bestScore">${Number(localStorage.getItem(BEST_KEY)||0)}</strong>`}const shareHeader=document.createElement('button');shareHeader.className='icon-button';shareHeader.id='shareGameButton';shareHeader.setAttribute('aria-label','Chia sẻ game');shareHeader.textContent='↗';actions.prepend(shareHeader);const welcomeShare=document.createElement('button');welcomeShare.className='secondary-button';welcomeShare.id='welcomeShareButton';welcomeShare.innerHTML='Chia sẻ game <span>↗</span>';$('#startButton').after(welcomeShare);const resultShare=document.createElement('button');resultShare.className='primary-button';resultShare.id='shareResultButton';resultShare.innerHTML='Thách bạn bè <span>↗</span>';$('#replayButton').before(resultShare);$('#replayButton').className='secondary-button';const footer=$('footer a');footer.href='../english-hub/';footer.textContent='← Về English Hub';$('.brand').href='../english-hub/';const toast=document.createElement('div');toast.className='toast';toast.id='toast';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');document.body.appendChild(toast);$('#startButton').setAttribute('aria-busy','true');if(mode==='daily'){const progress=loadDaily();const badge=document.createElement('p');badge.className='daily-streak';badge.id='dailyStreak';badge.textContent=progress.last===localDay()?`✅ Đã hoàn thành hôm nay · 🔥 ${progress.streak} ngày`:`🔥 Chuỗi hiện tại: ${progress.streak} ngày`;$('.welcome .intro').after(badge)}shareHeader.onclick=welcomeShare.onclick=()=>share(false);resultShare.onclick=()=>share(true);show('welcomeScreen')}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
async function share(result){const text=result?`Tôi được ${state.score} điểm trong ${config.name}. Bạn thử nhé!`:`Thử chơi ${config.name} trong English Hub!`;if(navigator.share){try{await navigator.share({title:config.name,text,url:location.href});return}catch(error){if(error.name==='AbortError')return}}try{await navigator.clipboard.writeText(`${text} ${location.href}`);toast('Đã sao chép đường dẫn')}catch{toast('Hãy sao chép đường dẫn trên thanh địa chỉ')}}
function localDay(offset=0){const date=new Date();date.setDate(date.getDate()+offset);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function seeded(items){let seed=[...localDay()].reduce((n,ch)=>n+ch.charCodeAt(0),0);const ranked=items.map(item=>{seed=(seed*9301+49297)%233280;return{item,rank:(itemIndex(item)+seed)%233280}});return ranked.sort((a,b)=>a.rank-b.rank).map(x=>x.item).slice(0,config.rounds)}
function deck(){const recent=new Set(loadList(RECENT_KEY));const fresh=shuffle(vocabulary.filter(item=>!recent.has(item.word)));const picked=(mode==='daily'?seeded(vocabulary):[...fresh,...shuffle(vocabulary)]).filter((item,i,list)=>list.findIndex(x=>x.word===item.word)===i).slice(0,config.rounds);saveList(RECENT_KEY,[...picked.map(x=>x.word),...loadList(RECENT_KEY)].slice(0,Math.max(0,vocabulary.length-config.rounds)));return picked}
function loadVocabulary(){const source=window.GAME_VOCABULARY_1000||[];const all=source.map(x=>({word:x.word,meaning:x.meaning,emoji:x.emoji||'🔤',example:x.example||''}));if(mode==='picture'){const iconCounts=new Map();all.forEach(item=>iconCounts.set(item.emoji,(iconCounts.get(item.emoji)||0)+1));vocabulary=all.filter(item=>item.emoji!=='🔤'&&iconCounts.get(item.emoji)===1)}else vocabulary=all;const button=$('#startButton');button.setAttribute('aria-busy','false');if(vocabulary.length){button.disabled=false;button.innerHTML=`Chơi ${config.name} <span>→</span>`}else{button.disabled=true;button.textContent='Không tải được dữ liệu · Thử tải lại trang';button.setAttribute('aria-label','Không tải được dữ liệu. Hãy tải lại trang.')}return Promise.resolve()}
function choices(answer,field='meaning'){const pool=[...new Set(vocabulary.map(x=>x[field]).filter(x=>x&&x!==answer))];return shuffle([answer,...shuffle(pool).slice(0,3)])}
function baseCard(item,label,word,question,icon=''){return `<article class="suite-card"><div class="prompt-icon">${icon}</div><p class="prompt-label">${label}</p><h2 class="prompt-word" data-speak="${item.word}">${word}</h2><button class="pronunciation" data-speak="${item.word}">🔊 Nghe phát âm</button>${question?`<p class="suite-question">${question}</p>`:''}<div class="feedback-line" id="feedbackLine"></div></article>`}
function render(){if(mode==='speed'&&state.seconds<=0)return finish();const item=state.deck[state.index%state.deck.length];state.answered=false;state.selected=[];$('#roundText').textContent=mode==='speed'?`Đã trả lời ${state.index}`:`Câu ${state.index+1}/${state.deck.length}`;$('#scoreText').textContent=state.score;$('#comboText').textContent=state.combo;$('#progressBar').style.width=mode==='speed'?`${state.seconds/60*100}%`:`${(state.index+1)/state.deck.length*100}%`;$('#nextButton').classList.remove('visible');$('#answerArea').innerHTML='';
  if(mode==='picture')renderPicture(item);
  else if(mode==='emoji')renderChoice(item,baseCard(item,'Emoji Vocabulary',item.word,'Chọn nghĩa đúng của từ.',item.emoji));
  else if(mode==='listening'){renderListening(item)}
  else if(mode==='grammar')renderGrammar(item);
  else if(mode==='sentence')renderSentence(item);
  else if(mode==='reading')renderReading(item);
  else if(mode==='typing')renderTyping(item);
  else renderChoice(item,baseCard(item,mode==='daily'?'Daily Challenge':'60s Challenge',item.word,'Chọn nghĩa đúng.',mode==='daily'?'🏆':'⚡'));
}
function renderChoice(item,card){$('#questionArea').innerHTML=card;$('#answerArea').innerHTML=`<div class="choice-grid">${choices(item.meaning).map(x=>`<button class="choice-button" data-value="${x}">${x}</button>`).join('')}</div>`;$$('.choice-button').forEach(btn=>btn.onclick=()=>mark(btn,btn.dataset.value===item.meaning,item.meaning))}
function renderPicture(item){const card=baseCard(item,'Icon Vocabulary','???','Nhìn biểu tượng và chọn từ tiếng Anh phù hợp.',item.emoji);$('#questionArea').innerHTML=card;$('.pronunciation').hidden=true;$('#answerArea').innerHTML=`<div class="choice-grid">${choices(item.word,'word').map(x=>`<button class="choice-button" data-value="${x}">${x}</button>`).join('')}</div>`;$$('.choice-button').forEach(btn=>btn.onclick=()=>mark(btn,btn.dataset.value===item.word,item.word))}
function renderListening(item){const card=baseCard(item,'Listening','???','Nghe kỹ rồi chọn nghĩa đúng.','🎧').replace('</article>',`<div class="listening-controls"><button type="button" id="listenAgain">🔊 Nghe lại</button><button type="button" id="listenSlow">🐢 Nghe chậm</button></div></article>`);renderChoice(item,card);$('#listenAgain').onclick=()=>window.EnglishSpeech?.speak(item.word,{force:true});$('#listenSlow').onclick=()=>window.EnglishSpeech?.speak(item.word,{rate:.58,force:true});setTimeout(()=>window.EnglishSpeech?.speak(item.word,{force:true}),300)}
function renderGrammar(item){const word=item.word;const templates=[{label:'Động từ nguyên mẫu',correct:`I want to learn the word “${word}”.`,wrong:[`I wants to learn the word “${word}”.`,`I want learning the word “${word}”.`,`I am want to learn the word “${word}”.`]},{label:'Thì hiện tại đơn',correct:`She practices “${word}” every day.`,wrong:[`She practice “${word}” every day.`,`She practicing “${word}” every day.`,`She is practice “${word}” every day.`]},{label:'Thì quá khứ đơn',correct:`We learned “${word}” yesterday.`,wrong:[`We learn “${word}” yesterday.`,`We learning “${word}” yesterday.`,`We have learn “${word}” yesterday.`]},{label:'Động từ khuyết thiếu',correct:`You can use “${word}” in a sentence.`,wrong:[`You can to use “${word}” in a sentence.`,`You can uses “${word}” in a sentence.`,`You can using “${word}” in a sentence.`]},{label:'Câu hỏi',correct:`Do you remember the word “${word}”?`,wrong:[`Are you remember the word “${word}”?`,`Do you remembers the word “${word}”?`,`Does you remember the word “${word}”?`]}];const task=templates[itemIndex(item,'grammar')%templates.length];const options=shuffle([task.correct,...task.wrong]);$('#questionArea').innerHTML=baseCard(item,`Grammar · ${task.label}`,word,'Chọn câu đúng ngữ pháp.','📝');$('#answerArea').innerHTML=`<div class="choice-grid">${options.map(x=>`<button class="choice-button" data-ok="${x===task.correct}">${x}</button>`).join('')}</div>`;$$('.choice-button').forEach(btn=>btn.onclick=()=>mark(btn,btn.dataset.ok==='true',task.correct))}
function renderSentence(item){const templates=[`I learned the word ${item.word} today`,`Please use ${item.word} in a sentence`,`We practice saying ${item.word} together`,`Can you remember the word ${item.word}`,`She wrote ${item.word} in her notebook`];const sentence=templates[itemIndex(item,'sentence')%templates.length];const words=shuffle(sentence.split(' '));$('#questionArea').innerHTML=baseCard(item,'Sentence Builder',item.word,'Sắp xếp các từ thành câu đúng.','🔧');$('#answerArea').innerHTML=`<div class="sentence-line" id="sentenceLine" aria-live="polite"></div><div class="word-tiles">${words.map((x,i)=>`<button class="word-tile" data-i="${i}" data-word="${x}">${x}</button>`).join('')}</div><button class="secondary-button undo-word" id="undoWord" disabled>↶ Hoàn tác</button>`;const refresh=()=>{$('#sentenceLine').textContent=state.selected.join(' ');$('#undoWord').disabled=!state.selected.length||state.answered};$$('.word-tile').forEach(btn=>btn.onclick=()=>{btn.disabled=true;state.selected.push(btn.dataset.word);refresh();if(state.selected.length===words.length){mark(btn,state.selected.join(' ')===sentence,sentence);refresh()}});$('#undoWord').onclick=()=>{if(state.answered)return;const word=state.selected.pop();const button=$$('.word-tile').reverse().find(x=>x.disabled&&x.dataset.word===word);if(button)button.disabled=false;refresh()}}
function renderReading(item){const readings=[{passage:`Mai keeps a small vocabulary notebook. Today she writes “${item.word}”, reads its meaning, and says it three times before class.`,question:'Mai làm gì để ghi nhớ từ mới?'},{passage:`Nam sees the word “${item.word}” in a story. He guesses its meaning from the sentence, then checks a dictionary after reading.`,question:'Nam kiểm tra nghĩa của từ khi nào?'},{passage:`Lan and Minh study together. Lan explains “${item.word}” while Minh creates a short example sentence with it.`,question:'Minh làm gì với từ mới?'},{passage:`The teacher puts “${item.word}” on the board. The class listens to its pronunciation and then uses it in pairs.`,question:'Cả lớp luyện từ mới như thế nào?'}];const reading=readings[itemIndex(item,'reading')%readings.length];const answers=reading.question.includes('ghi nhớ')?[`Viết, đọc nghĩa và nói lại ba lần`,`Chỉ nhìn từ một lần`,`Bỏ qua nghĩa của từ`,`Chép cả cuốn từ điển`]:reading.question.includes('khi nào')?[`Sau khi đọc xong`,`Trước khi thấy từ`,`Không bao giờ`,`Vào tuần sau`]:reading.question.includes('Minh')?[`Tạo một câu ví dụ`,`Xóa từ khỏi vở`,`Dịch cả cuốn sách`,`Không tham gia`]:[`Nghe phát âm rồi dùng từ theo cặp`,`Chỉ chép từ lên bảng`,`Không đọc từ`,`Học một mình ở nhà`];const correct=answers[0];$('#questionArea').innerHTML=baseCard(item,'Reading',item.word,'Đọc đoạn văn rồi trả lời câu hỏi.','📚').replace('</article>',`<p class="reading-passage">${reading.passage}</p></article>`);$('#answerArea').innerHTML=`<p class="suite-question">${reading.question}</p><div class="choice-grid">${shuffle(answers).map(x=>`<button class="choice-button" data-value="${x}">${x}</button>`).join('')}</div>`;$$('.choice-button').forEach(btn=>btn.onclick=()=>mark(btn,btn.dataset.value===correct,correct))}
function renderTyping(item){$('#questionArea').innerHTML=baseCard(item,'Typing','TYPE','Gõ từ tiếng Anh có nghĩa bên dưới.','⌨️').replace('</article>',`<p class="suite-question"><strong>${item.meaning}</strong></p></article>`);$('#answerArea').innerHTML=`<div class="text-answer"><input id="typingInput" autocomplete="off" spellcheck="false" aria-label="Nhập từ tiếng Anh"><button class="primary-button" id="submitTyping">Kiểm tra</button></div>`;$('#submitTyping').onclick=()=>mark($('#submitTyping'),$('#typingInput').value.trim().toLowerCase()===item.word.toLowerCase(),item.word);$('#typingInput').onkeydown=e=>{if(e.key==='Enter')$('#submitTyping').click()};$('#typingInput').focus()}
function mark(button,ok,answer){if(state.answered||state.finished)return;state.answered=true;$$('.choice-button,.word-tile').forEach(x=>x.disabled=true);if(ok){state.correct++;state.combo++;state.score+=100+(state.combo-1)*20;button.classList?.add('correct')}else{state.combo=0;button.classList?.add('wrong')}if(mode==='listening'||mode==='typing'||mode==='picture'){const word=state.deck[state.index%state.deck.length].word;const title=$('.prompt-word');title.textContent=word;title.dataset.speak=word;if(mode==='picture')$('.pronunciation').hidden=false}const line=$('#feedbackLine');if(line)line.textContent=ok?'✅ Chính xác!':`📘 Đáp án: ${answer}`;$('#scoreText').textContent=state.score;$('#comboText').textContent=state.combo;if(mode==='speed')nextTimerId=setTimeout(next,350);else $('#nextButton').classList.add('visible')}
function next(){state.index++;if(mode!=='speed'&&state.index>=state.deck.length)return finish();render()}
function finish(){if(state.finished)return;state.finished=true;clearInterval(timerId);clearTimeout(nextTimerId);const old=Number(localStorage.getItem(BEST_KEY)||0);if(state.score>old)localStorage.setItem(BEST_KEY,state.score);if($('#bestScore'))$('#bestScore').textContent=Math.max(old,state.score);$('#finalScore').textContent=state.score;$('#finalLine').textContent=`${state.correct} câu đúng`;$('#resultTitle').textContent=state.correct>=8?'English rất chắc!':'Chơi thêm một lượt để tiến bộ!';if(mode==='daily'){const progress=recordDaily();$('#finalLine').textContent=`${state.correct}/${state.deck.length} câu đúng · 🔥 ${progress.streak} ngày`;$('#resultTitle').textContent='Đã hoàn thành thử thách hôm nay!';const badge=$('#dailyStreak');if(badge)badge.textContent=`✅ Đã hoàn thành hôm nay · 🔥 ${progress.streak} ngày`}if(typeof recordGameScore==='function')recordGameScore(config.name,state.score,config.icon);show('resultScreen')}
async function start(){await ready;if(!vocabulary.length)return;clearInterval(timerId);clearTimeout(nextTimerId);state.deck=deck();state.index=0;state.score=0;state.correct=0;state.combo=0;state.seconds=60;state.finished=false;show('gameScreen');if(mode==='speed'){timerId=setInterval(()=>{state.seconds--;$('#timerText').textContent=`${state.seconds}s`;$('#progressBar').style.width=`${state.seconds/60*100}%`;if(state.seconds<=0)finish()},1000)}render()}
setupSharedLayout();const ready=loadVocabulary();$('#startButton').onclick=start;$('#replayButton').onclick=start;$('#nextButton').onclick=next;
