const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const questions=[
{pic:"🐝 🍯",hint:"Đọc gần âm và nghĩ tới cảm giác rất ngọt.",a:"Bí mật ngọt ngào",c:["Bí mật ngọt ngào","Con ong chăm chỉ","Mật mã tình yêu","Ngọt như mía lùi"],ex:"Ong + mật gợi chữ 'mật', kết hợp thành cụm có nghĩa bóng."},
{pic:"🐘 🐭",hint:"Một việc mở đầu rất lớn nhưng kết thúc quá nhỏ.",a:"Đầu voi đuôi chuột",c:["Đầu voi đuôi chuột","Voi chui lỗ kim","Chuột sa chĩnh gạo","Mèo mù vớ cá rán"],ex:"Hình voi và chuột gợi trực tiếp thành ngữ quen thuộc."},
{pic:"🌊 🧂",hint:"Một vùng nước rộng, vị mặn.",a:"Biển mặn",c:["Biển mặn","Nước mắt","Muối biển","Sóng gió"],ex:"Sóng nước + muối gợi ý biển và vị mặn."},
{pic:"🔥 🧊",hint:"Hai trạng thái trái ngược đặt cạnh nhau.",a:"Nóng lạnh",c:["Nóng lạnh","Lửa băng","Trái tính","Tâm trạng thất thường"],ex:"Lửa và đá là cặp đối lập nhiệt độ."},
{pic:"👂 🌬️",hint:"Nghe một chuyện thoáng qua, chưa chắc đáng tin.",a:"Nghe gió",c:["Nghe gió","Tai bay vạ gió","Gió thoảng bên tai","Nói gió nói mây"],ex:"Tai + gió gợi hành động nghe tin phong thanh."},
{pic:"🐟 🪵",hint:"Một con vật gặp đúng môi trường thuận lợi.",a:"Cá gặp nước",c:["Cá gặp nước","Cá nằm trên thớt","Nước đến chân","Thả cá về sông"],ex:"Cá và nước gợi thành ngữ về gặp điều kiện phù hợp."},
{pic:"🌱 🪨",hint:"Sự sống mọc lên trong hoàn cảnh rất khó.",a:"Mầm trên đá",c:["Mầm trên đá","Cây nhà lá vườn","Đá nở hoa","Gieo gì gặt nấy"],ex:"Mầm cây trên đá gợi ý vượt khó."},
{pic:"🧠 ⚡",hint:"Nghĩ rất nhanh, bật ra ý tưởng.",a:"Nhanh trí",c:["Nhanh trí","Đau đầu","Sét đánh ngang tai","Não cá vàng"],ex:"Não + tia chớp gợi tốc độ suy nghĩ."},
{pic:"🕳️ 🐸",hint:"Tầm nhìn hạn hẹp, chỉ biết thế giới nhỏ của mình.",a:"Ếch ngồi đáy giếng",c:["Ếch ngồi đáy giếng","Ếch kêu mùa mưa","Giếng sâu khó dò","Ngồi mát ăn bát vàng"],ex:"Hố/giếng và ếch là hình ảnh của thành ngữ này."},
{pic:"🥚 🪨",hint:"Lấy thứ yếu mềm chống lại thứ quá cứng.",a:"Lấy trứng chọi đá",c:["Lấy trứng chọi đá","Trứng khôn hơn vịt","Đá ném ao bèo","Cứng như đá"],ex:"Trứng và đá gợi sự chênh lệch lực."},
{pic:"🌧️ ☂️ 🏃",hint:"Chuẩn bị muộn khi sự việc đã xảy ra.",a:"Nước đến chân mới nhảy",c:["Nước đến chân mới nhảy","Chạy mưa không kịp","Mưa dầm thấm lâu","Phòng bệnh hơn chữa bệnh"],ex:"Mưa/nước và chạy gợi phản ứng vội vàng phút cuối."},
{pic:"👀 🌸 🐎",hint:"Xem qua loa, không quan sát kỹ.",a:"Cưỡi ngựa xem hoa",c:["Cưỡi ngựa xem hoa","Hoa mắt chóng mặt","Ngựa quen đường cũ","Mắt thấy tai nghe"],ex:"Mắt + hoa + ngựa gợi thành ngữ quen thuộc."}
];
const state={deck:[],i:0,score:0,correct:0,streak:0};
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}function show(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id))}function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}function best(){$("#bestScore").textContent=Number(localStorage.getItem("doan-hinh-bat-chu-best")||0)}
function start(){state.deck=shuffle(questions).slice(0,10);state.i=0;state.score=0;state.correct=0;state.streak=0;show("gameScreen");render()}function render(){const q=state.deck[state.i];$("#roundText").textContent=`Câu ${state.i+1}/${state.deck.length}`;$("#scoreText").textContent=state.score;$("#progressBar").style.width=`${((state.i+1)/state.deck.length)*100}%`;$("#pictureClue").textContent=q.pic;$("#hintText").textContent=q.hint;$("#answerGrid").innerHTML=shuffle(q.c).map(c=>`<button class="answer-button" data-a="${c}">${c}</button>`).join("");$$(".answer-button").forEach(b=>b.onclick=()=>answer(b,q))}
function answer(btn,q){const ok=btn.dataset.a===q.a;$$(".answer-button").forEach(b=>{b.disabled=true;if(b.dataset.a===q.a)b.classList.add("correct")});if(!ok)btn.classList.add("wrong");if(ok){state.score+=100+state.streak*25;state.correct++;state.streak++;$("#feedbackIcon").textContent="🎯";$("#feedbackLabel").textContent="Bắt đúng chữ";}else{state.streak=0;$("#feedbackIcon").textContent="🔍";$("#feedbackLabel").textContent="Chưa khớp"}$("#feedbackTitle").textContent=q.a;$("#feedbackText").textContent=q.ex;state.i++;setTimeout(()=>show("feedbackScreen"),400)}
function next(){if(state.i>=state.deck.length)return finish();show("gameScreen");render()}function finish(){const old=Number(localStorage.getItem("doan-hinh-bat-chu-best")||0);if(state.score>old)localStorage.setItem("doan-hinh-bat-chu-best",state.score);best();$("#resultTitle").textContent=state.correct>=9?"Bắt chữ cực bén!":state.correct>=7?"Suy luận hình ảnh rất tốt!":state.correct>=5?"Đã vào guồng rồi!":"Chơi lại là lên tay ngay!";$("#finalScore").textContent=state.score;$("#finalCorrect").textContent=`${state.correct}/${state.deck.length} câu đúng`;if(typeof recordGameScore==='function'){recordGameScore('Đoán Hình Bắt Chữ',state.score,'🖼️');}show("resultScreen")}
async function share(text,msg){const url=location.origin+location.pathname;if(navigator.share){try{await navigator.share({title:"Đoán Hình Bắt Chữ",text,url});return}catch(e){if(e.name==="AbortError")return}}await navigator.clipboard.writeText(`${text} ${url}`);toast(msg)}
$("#startButton").onclick=start;$("#replayButton").onclick=start;$("#nextButton").onclick=next;$("#shareGameButton").onclick=()=>share("Thử chơi Đoán Hình Bắt Chữ: nhìn hình gợi ý và chọn cụm từ đúng.","Đã sao chép link game");$("#welcomeShareButton").onclick=$("#shareGameButton").onclick;$("#shareResultButton").onclick=()=>share(`Tôi được ${state.score} điểm trong Đoán Hình Bắt Chữ, đúng ${state.correct}/${state.deck.length} câu.`, "Đã sao chép lời thách");best();
