const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const mode = document.body.dataset.mode;
const config = {
  picture:{name:"Picture Vocabulary",icon:"🖼️",rounds:12}, emoji:{name:"Emoji Vocabulary",icon:"😊",rounds:12}, grammar:{name:"Grammar Quiz",icon:"📝",rounds:12},
  sentence:{name:"Sentence Builder",icon:"🔧",rounds:10}, listening:{name:"Listening",icon:"🔊",rounds:12}, reading:{name:"Reading",icon:"📚",rounds:10},
  typing:{name:"Typing",icon:"⌨️",rounds:12}, daily:{name:"Daily Challenge",icon:"🏆",rounds:10}, speed:{name:"60s Challenge",icon:"🎯",rounds:999}
}[mode];
let vocabulary = [], timerId = null;
const state = {deck:[],index:0,score:0,correct:0,combo:0,answered:false,selected:[],seconds:60};
const RECENT_KEY = `english-${mode}-recent`;
const BEST_KEY = `english-${mode}-best`;
const shuffle = items => [...items].sort(() => Math.random() - .5);
function loadList(key){try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return[]}}
function saveList(key,list){localStorage.setItem(key,JSON.stringify([...new Set(list)]))}
function show(id){$$('.screen').forEach(el=>el.classList.toggle('active',el.id===id))}
function setupSharedLayout(){const actions=$('.header-actions');const status=$('#timerText');if(mode==='speed')status.textContent='60s';else{status.classList.remove('timer');status.innerHTML=`Kỷ lục <strong id="bestScore">${Number(localStorage.getItem(BEST_KEY)||0)}</strong>`}const shareHeader=document.createElement('button');shareHeader.className='icon-button';shareHeader.id='shareGameButton';shareHeader.setAttribute('aria-label','Chia sẻ game');shareHeader.textContent='↗';actions.prepend(shareHeader);const welcomeShare=document.createElement('button');welcomeShare.className='secondary-button';welcomeShare.id='welcomeShareButton';welcomeShare.innerHTML='Chia sẻ game <span>↗</span>';$('#startButton').after(welcomeShare);const resultShare=document.createElement('button');resultShare.className='primary-button';resultShare.id='shareResultButton';resultShare.innerHTML='Thách bạn bè <span>↗</span>';$('#replayButton').before(resultShare);$('#replayButton').className='secondary-button';const footer=$('footer a');footer.href='../';footer.textContent='← Về cổng game';$('.brand').href='../';const toast=document.createElement('div');toast.className='toast';toast.id='toast';toast.setAttribute('role','status');document.body.appendChild(toast);shareHeader.onclick=welcomeShare.onclick=()=>share(false);resultShare.onclick=()=>share(true)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
async function share(result){const text=result?`Tôi được ${state.score} điểm trong ${config.name}. Bạn thử nhé!`:`Thử chơi ${config.name} trong English Hub!`;if(navigator.share){try{await navigator.share({title:config.name,text,url:location.href});return}catch(error){if(error.name==='AbortError')return}}try{await navigator.clipboard.writeText(`${text} ${location.href}`);toast('Đã sao chép đường dẫn')}catch{toast('Hãy sao chép đường dẫn trên thanh địa chỉ')}}
function seeded(items){const day=new Date().toISOString().slice(0,10);let seed=[...day].reduce((n,ch)=>n+ch.charCodeAt(0),0);return [...items].sort((a,b)=>{seed=(seed*9301+49297)%233280;return ((a.word.charCodeAt(0)+seed)%997)-((b.word.charCodeAt(0)+seed)%991)}).slice(0,config.rounds)}
function deck(){const recent=new Set(loadList(RECENT_KEY));const fresh=shuffle(vocabulary.filter(item=>!recent.has(item.word)));const picked=(mode==='daily'?seeded(vocabulary):[...fresh,...shuffle(vocabulary)]).filter((item,i,list)=>list.findIndex(x=>x.word===item.word)===i).slice(0,config.rounds);saveList(RECENT_KEY,[...picked.map(x=>x.word),...loadList(RECENT_KEY)].slice(0,Math.max(0,vocabulary.length-config.rounds)));return picked}
function loadVocabulary(){return new Promise(resolve=>{const frame=document.createElement('iframe');frame.hidden=true;frame.setAttribute('aria-hidden','true');let finished=false;const done=()=>{if(finished)return;finished=true;frame.remove();$('#startButton').disabled=false;$('#startButton').innerHTML=`Chơi ${config.name} <span>→</span>`;resolve()};frame.onload=()=>{vocabulary=(frame.contentWindow?.GAME_VOCABULARY_1000||[]).map(x=>({word:x.word,meaning:x.meaning,emoji:x.emoji||'🔤',example:x.example||''}));done()};frame.onerror=done;frame.src='../doan-tu-tieng-anh/';document.body.appendChild(frame);setTimeout(done,8000)})}
const ready=loadVocabulary();
function choices(answer,field='meaning'){const pool=[...new Set(vocabulary.map(x=>x[field]).filter(x=>x&&x!==answer))];return shuffle([answer,...shuffle(pool).slice(0,3)])}
function baseCard(item,label,word,question,icon=''){return `<article class="suite-card"><div class="prompt-icon">${icon}</div><p class="prompt-label">${label}</p><h2 class="prompt-word" data-speak="${item.word}">${word}</h2><button class="pronunciation" data-speak="${item.word}">🔊 Nghe phát âm</button>${question?`<p class="suite-question">${question}</p>`:''}<div class="feedback-line" id="feedbackLine"></div></article>`}
function render(){if(mode==='speed'&&state.seconds<=0)return finish();const item=state.deck[state.index%state.deck.length];state.answered=false;state.selected=[];$('#roundText').textContent=mode==='speed'?`Đã trả lời ${state.index}`:`Câu ${state.index+1}/${state.deck.length}`;$('#scoreText').textContent=state.score;$('#comboText').textContent=state.combo;$('#progressBar').style.width=mode==='speed'?`${state.seconds/60*100}%`:`${(state.index+1)/state.deck.length*100}%`;$('#nextButton').classList.remove('visible');$('#answerArea').innerHTML='';
  if(mode==='picture'||mode==='emoji')renderChoice(item,baseCard(item,mode==='picture'?'Picture Vocabulary':'Emoji Vocabulary',item.word,'Chọn nghĩa đúng của từ.',item.emoji));
  else if(mode==='listening'){renderChoice(item,baseCard(item,'Listening','???','Nghe từ rồi chọn nghĩa đúng.','🎧'));setTimeout(()=>window.EnglishSpeech?.speak(item.word),300)}
  else if(mode==='grammar')renderGrammar(item);
  else if(mode==='sentence')renderSentence(item);
  else if(mode==='reading')renderReading(item);
  else if(mode==='typing')renderTyping(item);
  else renderChoice(item,baseCard(item,mode==='daily'?'Daily Challenge':'60s Challenge',item.word,'Chọn nghĩa đúng.',mode==='daily'?'🏆':'⚡'));
}
function renderChoice(item,card){$('#questionArea').innerHTML=card;$('#answerArea').innerHTML=`<div class="choice-grid">${choices(item.meaning).map(x=>`<button class="choice-button" data-value="${x}">${x}</button>`).join('')}</div>`;$$('.choice-button').forEach(btn=>btn.onclick=()=>mark(btn,btn.dataset.value===item.meaning,item.meaning))}
function renderGrammar(item){const correct=`I want to learn the word “${item.word}”.`;const options=shuffle([correct,`I wants to learn the word “${item.word}”.`,`I want learning the word “${item.word}”.`,`I am want to learn the word “${item.word}”.`]);$('#questionArea').innerHTML=baseCard(item,'Grammar Quiz',item.word,'Chọn câu đúng ngữ pháp.','📝');$('#answerArea').innerHTML=`<div class="choice-grid">${options.map(x=>`<button class="choice-button" data-ok="${x===correct}">${x}</button>`).join('')}</div>`;$$('.choice-button').forEach(btn=>btn.onclick=()=>mark(btn,btn.dataset.ok==='true',correct))}
function renderSentence(item){const sentence=`I learn the word ${item.word} today`;const words=shuffle(sentence.split(' '));$('#questionArea').innerHTML=baseCard(item,'Sentence Builder',item.word,'Sắp xếp các từ thành câu đúng.','🔧');$('#answerArea').innerHTML=`<div class="sentence-line" id="sentenceLine"></div><div class="word-tiles">${words.map((x,i)=>`<button class="word-tile" data-i="${i}" data-word="${x}">${x}</button>`).join('')}</div>`;$$('.word-tile').forEach(btn=>btn.onclick=()=>{btn.disabled=true;state.selected.push(btn.dataset.word);$('#sentenceLine').textContent=state.selected.join(' ');if(state.selected.length===words.length)mark(btn,state.selected.join(' ')===sentence,sentence)})}
function renderReading(item){const passage=`Mai is learning English today. She writes the word “${item.word}” in her notebook and practices saying it aloud. She wants to remember this new vocabulary for tomorrow.`;$('#questionArea').innerHTML=baseCard(item,'Reading',item.word,'Đọc đoạn văn rồi trả lời câu hỏi.','📚').replace('</article>',`<p class="reading-passage">${passage}</p></article>`);$('#answerArea').innerHTML=`<p class="suite-question">Mai đã viết từ nào vào vở?</p><div class="choice-grid">${choices(item.word,'word').map(x=>`<button class="choice-button" data-value="${x}">${x}</button>`).join('')}</div>`;$$('.choice-button').forEach(btn=>btn.onclick=()=>mark(btn,btn.dataset.value===item.word,item.word))}
function renderTyping(item){$('#questionArea').innerHTML=baseCard(item,'Typing','TYPE','Gõ từ tiếng Anh có nghĩa bên dưới.','⌨️').replace('</article>',`<p class="suite-question"><strong>${item.meaning}</strong></p></article>`);$('#answerArea').innerHTML=`<div class="text-answer"><input id="typingInput" autocomplete="off" spellcheck="false" aria-label="Nhập từ tiếng Anh"><button class="primary-button" id="submitTyping">Kiểm tra</button></div>`;$('#submitTyping').onclick=()=>mark($('#submitTyping'),$('#typingInput').value.trim().toLowerCase()===item.word.toLowerCase(),item.word);$('#typingInput').onkeydown=e=>{if(e.key==='Enter')$('#submitTyping').click()};$('#typingInput').focus()}
function mark(button,ok,answer){if(state.answered)return;state.answered=true;$$('.choice-button,.word-tile').forEach(x=>x.disabled=true);if(ok){state.correct++;state.combo++;state.score+=100+(state.combo-1)*20;button.classList?.add('correct')}else{state.combo=0;button.classList?.add('wrong')}if(mode==='listening'||mode==='typing'){const word=state.deck[state.index%state.deck.length].word;const title=$('.prompt-word');title.textContent=word;title.dataset.speak=word}const line=$('#feedbackLine');if(line)line.textContent=ok?'✅ Chính xác!':`📘 Đáp án: ${answer}`;$('#scoreText').textContent=state.score;$('#comboText').textContent=state.combo;if(mode==='speed')setTimeout(next,350);else $('#nextButton').classList.add('visible')}
function next(){state.index++;if(mode!=='speed'&&state.index>=state.deck.length)return finish();render()}
function finish(){clearInterval(timerId);const old=Number(localStorage.getItem(BEST_KEY)||0);if(state.score>old)localStorage.setItem(BEST_KEY,state.score);if($('#bestScore'))$('#bestScore').textContent=Math.max(old,state.score);$('#finalScore').textContent=state.score;$('#finalLine').textContent=`${state.correct} câu đúng`;$('#resultTitle').textContent=state.correct>=8?'English rất chắc!':'Chơi thêm một lượt để tiến bộ!';if(typeof recordGameScore==='function')recordGameScore(config.name,state.score,config.icon);show('resultScreen')}
async function start(){await ready;if(!vocabulary.length)return;state.deck=deck();state.index=0;state.score=0;state.correct=0;state.combo=0;state.seconds=60;show('gameScreen');if(mode==='speed'){timerId=setInterval(()=>{state.seconds--;$('#timerText').textContent=`${state.seconds}s`;$('#progressBar').style.width=`${state.seconds/60*100}%`;if(state.seconds<=0)finish()},1000)}render()}
setupSharedLayout();$('#startButton').onclick=start;$('#replayButton').onclick=start;$('#nextButton').onclick=next;
