const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const baseData=[["BALANCE","sự cân bằng"],["COURAGE","lòng can đảm"],["JOURNEY","hành trình"],["MYSTERY","điều bí ẩn"],["PICTURE","bức tranh"],["WEATHER","thời tiết"],["FRIEND","người bạn"],["LIBRARY","thư viện"],["KITCHEN","nhà bếp"],["MORNING","buổi sáng"],["NATURE","thiên nhiên"],["PROBLEM","vấn đề"],["SILENCE","sự im lặng"],["TEACHER","giáo viên"],["VILLAGE","ngôi làng"],["WINDOW","cửa sổ"],["FREEDOM","sự tự do"],["HISTORY","lịch sử"],["HEALTH","sức khỏe"],["GARDEN","khu vườn"],["FUTURE","tương lai"],["MEMORY","trí nhớ"],["RESPECT","sự tôn trọng"],["CONNECT","kết nối"],["EXPLORE","khám phá"],["PROTECT","bảo vệ"],["IMPROVE","cải thiện"],["DISCOVER","khám phá ra"],["CREATIVE","sáng tạo"],["PATIENT","kiên nhẫn"]];
const data=[...new Map([...baseData,...(window.GAME_WORD_BANK_1000||[]).map(w=>[w,`từ tiếng Anh ${w.length} chữ`])].map(item=>[item[0],item])).values()].slice(0,1000);
let st={deck:[],i:0,score:0,correct:0,picked:[],used:[]};function sh(a){return[...a].sort(()=>Math.random()-.5)}function show(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id))}function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}function best(){$("#bestScore").textContent=Number(localStorage.getItem("unscramble-best")||0)}
function start(){st={deck:sh(data).slice(0,10),i:0,score:0,correct:0,picked:[],used:[]};show("gameScreen");render()}function scramble(w){let a=w.split("");do{a=sh(a)}while(a.join("")===w);return a}
function render(){const [w,h]=st.deck[st.i];if(!st.letters)st.letters=scramble(w);$("#roundText").textContent=`Câu ${st.i+1}/${st.deck.length}`;$("#scoreText").textContent=st.score;$("#progressBar").style.width=`${((st.i+1)/st.deck.length)*100}%`;$("#hintText").textContent=h;$("#answerSlots").innerHTML=w.split("").map((_,i)=>`<div class="slot">${st.picked[i]?.ch||""}</div>`).join("");$("#tileBank").innerHTML=st.letters.map((ch,i)=>`<button class="letter-tile" ${st.used.includes(i)?"disabled":""} data-i="${i}">${ch}</button>`).join("");$$(".letter-tile").forEach(b=>b.onclick=()=>pick(Number(b.dataset.i)))}
function pick(i){const [w]=st.deck[st.i];if(st.picked.length>=w.length)return;st.picked.push({ch:st.letters[i],i});st.used.push(i);if(st.picked.length===w.length)setTimeout(check,100);render()}function clear(){st.picked=[];st.used=[];render()}
function check(){const [w,h]=st.deck[st.i],ans=st.picked.map(x=>x.ch).join("");const ok=ans===w;if(ok){st.score+=100+w.length*10;st.correct++;$("#feedbackIcon").textContent="✅";$("#feedbackLabel").textContent="Đúng rồi"}else{$("#feedbackIcon").textContent="🔀";$("#feedbackLabel").textContent="Chưa đúng"}$("#feedbackTitle").textContent=w;$("#feedbackText").textContent=`${w} = ${h}`;st.i++;st.picked=[];st.used=[];st.letters=null;show("feedbackScreen")}
function next(){if(st.i>=st.deck.length)return finish();show("gameScreen");render()}function finish(){const old=Number(localStorage.getItem("unscramble-best")||0);if(st.score>old)localStorage.setItem("unscramble-best",st.score);best();$("#finalScore").textContent=st.score;$("#finalCorrect").textContent=`${st.correct}/${st.deck.length} từ đúng`;if(typeof recordGameScore==='function'){recordGameScore('Unscramble',st.score,'🔀');}show("resultScreen")}
async function share(text,msg){const url=location.origin+location.pathname;if(navigator.share){try{await navigator.share({title:"Unscramble",text,url});return}catch(e){if(e.name==="AbortError")return}}await navigator.clipboard.writeText(`${text} ${url}`);toast(msg)}
$("#startButton").onclick=start;$("#replayButton").onclick=start;$("#nextButton").onclick=next;$("#clearButton").onclick=clear;$("#shareGameButton").onclick=()=>share("Thử chơi Unscramble: sắp xếp chữ cái thành từ tiếng Anh đúng.","Đã sao chép link game");$("#welcomeShareButton").onclick=$("#shareGameButton").onclick;$("#shareResultButton").onclick=()=>share(`Tôi được ${st.score} điểm trong Unscramble, đúng ${st.correct}/${st.deck.length} từ.`, "Đã sao chép lời thách");best();
