const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const baseData=[["PLANET","hành tinh","RSM"],["FOREST","khu rừng","AIP"],["BRIDGE","cây cầu / kết nối","TOL"],["PUZZLE","câu đố","ARX"],["GARDEN","khu vườn","HIO"],["MARKET","chợ","NPL"],["ISLAND","hòn đảo","CER"],["ORANGE","quả cam / màu cam","TIS"],["POCKET","túi nhỏ","NAR"],["SILVER","màu bạc","TAN"],["THUNDER","sấm","AIC"],["JOURNAL","nhật ký","SME"],["LIBRARY","thư viện","CON"],["DIAMOND","kim cương","RSE"],["BALLOON","bóng bay","CAT"],["CANDLE","cây nến","RIO"],["MONSTER","quái vật","CAL"],["RAINBOW","cầu vồng","DSE"],["KINGDOM","vương quốc","PLA"],["MORNING","buổi sáng","SET"],["FLOWER","bông hoa","GIN"],["HAMMER","cái búa","TOL"],["ROCKET","tên lửa","AIN"],["TUNNEL","đường hầm","CAR"],["WINDOW","cửa sổ","FAN"],["CASTLE","lâu đài","RIN"],["BUTTON","nút bấm","LSE"],["PENCIL","bút chì","ARO"],["BOTTLE","chai/lọ","RIN"],["CAMERA","máy ảnh","TOL"]];
function extraLetters(word){return "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").filter(ch=>!word.includes(ch)).sort(()=>Math.random()-.5).slice(0,3).join("")}
const data=[...new Map([...baseData,...(window.GAME_WORD_BANK_1000||[]).map(w=>[w,`từ tiếng Anh ${w.length} chữ`,extraLetters(w)])].map(item=>[item[0],item])).values()].slice(0,1000);
let st={deck:[],i:0,score:0,correct:0,picked:[],used:[],letters:[]};function sh(a){return[...a].sort(()=>Math.random()-.5)}function show(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id))}function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),1800)}function best(){$("#bestScore").textContent=Number(localStorage.getItem("ghep-chu-best")||0)}
function start(){st={deck:sh(data).slice(0,10),i:0,score:0,correct:0,picked:[],used:[],letters:[]};show("gameScreen");newLetters();render()}function newLetters(){const [w,,extra]=st.deck[st.i];st.letters=sh((w+extra).split(""))}
function render(){const [w,h]=st.deck[st.i];$("#roundText").textContent=`Câu ${st.i+1}/${st.deck.length}`;$("#scoreText").textContent=st.score;$("#progressBar").style.width=`${((st.i+1)/st.deck.length)*100}%`;$("#hintText").textContent=h;$("#answerSlots").innerHTML=w.split("").map((_,i)=>`<div class="slot">${st.picked[i]?.ch||""}</div>`).join("");$("#tileBank").innerHTML=st.letters.map((ch,i)=>`<button class="letter-tile extra" ${st.used.includes(i)?"disabled":""} data-i="${i}">${ch}</button>`).join("");$$(".letter-tile").forEach(b=>b.onclick=()=>pick(Number(b.dataset.i)))}
function pick(i){const [w]=st.deck[st.i];if(st.picked.length>=w.length)return;st.picked.push({ch:st.letters[i],i});st.used.push(i);if(st.picked.length===w.length)setTimeout(check,100);render()}function clear(){st.picked=[];st.used=[];render()}
function check(){const [w,h]=st.deck[st.i],ans=st.picked.map(x=>x.ch).join("");const ok=ans===w;if(ok){st.score+=120+w.length*8;st.correct++;$("#feedbackIcon").textContent="✅";$("#feedbackLabel").textContent="Ghép đúng"}else{$("#feedbackIcon").textContent="🔤";$("#feedbackLabel").textContent="Chưa đúng"}$("#feedbackTitle").textContent=w;$("#feedbackText").textContent=`${w} = ${h}`;st.i++;st.picked=[];st.used=[];if(st.i<st.deck.length)newLetters();show("feedbackScreen")}
function next(){if(st.i>=st.deck.length)return finish();show("gameScreen");render()}function finish(){const old=Number(localStorage.getItem("ghep-chu-best")||0);if(st.score>old)localStorage.setItem("ghep-chu-best",st.score);best();$("#finalScore").textContent=st.score;$("#finalCorrect").textContent=`${st.correct}/${st.deck.length} từ đúng`;if(typeof recordGameScore==='function'){recordGameScore('Ghép Chữ Thành Từ',st.score,'🔤');}show("resultScreen")}
async function share(text,msg){const url=location.origin+location.pathname;if(navigator.share){try{await navigator.share({title:"Ghép chữ thành từ",text,url});return}catch(e){if(e.name==="AbortError")return}}await navigator.clipboard.writeText(`${text} ${url}`);toast(msg)}
$("#startButton").onclick=start;$("#replayButton").onclick=start;$("#nextButton").onclick=next;$("#clearButton").onclick=clear;$("#shareGameButton").onclick=()=>share("Thử chơi Ghép chữ thành từ: chọn chữ cái đúng để dựng từ theo gợi ý.","Đã sao chép link game");$("#welcomeShareButton").onclick=$("#shareGameButton").onclick;$("#shareResultButton").onclick=()=>share(`Tôi được ${st.score} điểm trong Ghép chữ thành từ, đúng ${st.correct}/${st.deck.length} từ.`, "Đã sao chép lời thách");best();
