const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const topics={
"Địa lý 🌍":[["Thủ đô của Nhật Bản là gì?","Tokyo",["Tokyo","Kyoto","Osaka","Seoul"],"Tokyo là thủ đô hiện tại của Nhật Bản."],["Sông Nile nằm chủ yếu ở châu lục nào?","Châu Phi",["Châu Phi","Châu Á","Châu Âu","Nam Mỹ"],"Nile là con sông nổi tiếng của châu Phi."],["Sa mạc Sahara thuộc khu vực nào?","Bắc Phi",["Bắc Phi","Nam Âu","Tây Á","Úc"],"Sahara trải dài qua nhiều quốc gia Bắc Phi."],["Quốc gia nào có hình chiếc ủng trên bản đồ?","Ý",["Ý","Pháp","Hy Lạp","Tây Ban Nha"],"Bản đồ nước Ý thường được ví như chiếc ủng."],["Everest thuộc dãy núi nào?","Himalaya",["Himalaya","Alps","Andes","Rocky"],"Everest nằm trong dãy Himalaya."],["Việt Nam nằm ở khu vực nào?","Đông Nam Á",["Đông Nam Á","Đông Á","Nam Á","Trung Á"],"Việt Nam thuộc Đông Nam Á."],["Đại dương lớn nhất là gì?","Thái Bình Dương",["Thái Bình Dương","Đại Tây Dương","Ấn Độ Dương","Bắc Băng Dương"],"Thái Bình Dương là đại dương lớn nhất."],["Kim tự tháp Giza ở nước nào?","Ai Cập",["Ai Cập","Mexico","Ấn Độ","Peru"],"Giza là quần thể kim tự tháp nổi tiếng tại Ai Cập."]],
"Khoa học 🔬":[["Hành tinh gần Mặt Trời nhất là gì?","Sao Thủy",["Sao Thủy","Sao Kim","Trái Đất","Sao Hỏa"],"Sao Thủy nằm gần Mặt Trời nhất."],["Nước có công thức hóa học nào?","H2O",["H2O","CO2","O2","NaCl"],"Một phân tử nước gồm 2 hydro và 1 oxy."],["Cơ quan nào bơm máu trong cơ thể?","Tim",["Tim","Phổi","Gan","Thận"],"Tim có nhiệm vụ bơm máu."],["Ánh sáng đi nhanh hơn âm thanh đúng không?","Đúng",["Đúng","Sai","Tùy thời tiết","Chỉ ban ngày"],"Ánh sáng nhanh hơn âm thanh rất nhiều."],["Loài cây tạo thức ăn nhờ quá trình gì?","Quang hợp",["Quang hợp","Hô hấp","Bay hơi","Đóng băng"],"Quang hợp giúp cây tạo chất hữu cơ."],["Khí nào cần cho hô hấp của người?","Oxy",["Oxy","Nitơ","Heli","CO2"],"Con người cần oxy để hô hấp."],["Trái Đất quay quanh gì?","Mặt Trời",["Mặt Trời","Mặt Trăng","Sao Hỏa","Sao Kim"],"Trái Đất quay quanh Mặt Trời."],["Nam châm hút mạnh vật liệu nào?","Sắt",["Sắt","Gỗ","Nhựa","Giấy"],"Sắt là vật liệu bị nam châm hút."]],
"Phim ảnh 🎬":[["Nhân vật nào là phù thủy trẻ có vết sẹo tia chớp?","Harry Potter",["Harry Potter","Frodo","Percy Jackson","Peter Pan"],"Harry Potter có vết sẹo hình tia chớp."],["Trong Frozen, Elsa có sức mạnh gì?","Băng tuyết",["Băng tuyết","Lửa","Tàng hình","Bay"],"Elsa điều khiển băng tuyết."],["Spider-Man thường bắn ra gì?","Tơ nhện",["Tơ nhện","Laser","Nước","Lửa"],"Spider-Man nổi tiếng với tơ nhện."],["Toy Story xoay quanh nhóm gì?","Đồ chơi",["Đồ chơi","Xe đua","Robot","Khủng long"],"Toy Story kể về các món đồ chơi sống động."],["Minions có màu chủ đạo gì?","Vàng",["Vàng","Xanh","Đỏ","Tím"],"Minions nổi tiếng với màu vàng."],["Batman sống ở thành phố hư cấu nào?","Gotham",["Gotham","Metropolis","Wakanda","Asgard"],"Batman gắn liền với Gotham."],["Nhân vật chính trong Moana thích điều gì?","Biển cả",["Biển cả","Sa mạc","Tuyết","Không gian"],"Moana có hành trình gắn với biển."],["Kung Fu Panda có nhân vật gấu trúc tên gì?","Po",["Po","Pikachu","Dory","Shrek"],"Po là chú gấu trúc học kung fu."]],
"Đời sống 🧩":[["Việc ngủ đủ giúp điều gì?","Phục hồi năng lượng",["Phục hồi năng lượng","Tăng tiếng ồn","Giảm trí nhớ","Làm mất nước"],"Ngủ đủ giúp cơ thể phục hồi."],["Đèn đỏ giao thông nghĩa là gì?","Dừng lại",["Dừng lại","Đi nhanh","Rẽ phải luôn","Bấm còi"],"Đèn đỏ yêu cầu dừng lại."],["Rửa tay giúp giảm nguy cơ gì?","Lây bệnh",["Lây bệnh","Buồn ngủ","Mất sóng","Mỏi mắt"],"Rửa tay giúp hạn chế mầm bệnh."],["Đọc nhãn thực phẩm giúp biết gì?","Thành phần",["Thành phần","Mật khẩu","Thời tiết","Địa chỉ nhà"],"Nhãn cho biết thành phần và thông tin sản phẩm."],["Tiết kiệm tiền nên bắt đầu bằng gì?","Ghi chi tiêu",["Ghi chi tiêu","Mua thêm đồ","Quên hóa đơn","Vay nhiều hơn"],"Ghi chi tiêu giúp biết tiền đi đâu."],["Tập thể dục đều giúp gì?","Khỏe hơn",["Khỏe hơn","Mất ngủ hơn","Quên đường","Tăng bụi"],"Vận động đều giúp cải thiện sức khỏe."],["Khi gặp tin lạ trên mạng nên làm gì?","Kiểm tra nguồn",["Kiểm tra nguồn","Chia sẻ ngay","Tin tuyệt đối","Bỏ qua mọi thứ"],"Kiểm tra nguồn giúp tránh tin sai."],["Uống nước đủ giúp cơ thể tránh gì?","Mất nước",["Mất nước","Mất chìa khóa","Mất sóng","Mất lịch"],"Nước cần thiết cho cơ thể."]]
};
function buildQuizQuestions(limit){const items=[];for(let a=1;items.length<limit&&a<=80;a++){for(let b=1;items.length<limit&&b<=40;b++){const sum=a+b;items.push([`${a} + ${b} bằng mấy?`,String(sum),[String(sum),String(sum+1),String(Math.max(0,sum-1)),String(sum+2)],`${a} cộng ${b} bằng ${sum}.`]);if(items.length>=limit)break;if(a>=b){const diff=a-b;items.push([`${a} - ${b} bằng mấy?`,String(diff),[String(diff),String(diff+1),String(Math.max(0,diff-1)),String(diff+2)],`${a} trừ ${b} bằng ${diff}.`])}}}return items}
{const current=Object.values(topics).reduce((total,items)=>total+items.length,0);topics["Toán nhanh 🧮"]=buildQuizQuestions(Math.max(0,1000-current))}
let selected=Object.keys(topics)[0];const state={deck:[],i:0,score:0,correct:0,streak:0};
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}function show(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id))}function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}function best(){$("#bestScore").textContent=Number(localStorage.getItem("quiz-theo-chu-de-best")||0)}
function renderTopics(){$("#topicGrid").innerHTML=Object.keys(topics).map(t=>`<button class="topic-button ${t===selected?"active":""}" data-topic="${t}">${t}</button>`).join("");$$(".topic-button").forEach(b=>b.onclick=()=>{selected=b.dataset.topic;renderTopics()})}
function start(){state.deck=shuffle(topics[selected]).slice(0,8);state.i=0;state.score=0;state.correct=0;state.streak=0;show("gameScreen");render()}function render(){const q=state.deck[state.i];$("#roundText").textContent=`Câu ${state.i+1}/${state.deck.length}`;$("#scoreText").textContent=state.score;$("#progressBar").style.width=`${((state.i+1)/state.deck.length)*100}%`;$("#topicText").textContent=selected;$("#questionText").textContent=q[0];$("#hintText").textContent="Chọn một đáp án.";$("#answerGrid").innerHTML=shuffle(q[2]).map(c=>`<button class="answer-button" data-a="${c}">${c}</button>`).join("");$$(".answer-button").forEach(b=>b.onclick=()=>answer(b,q))}
function answer(btn,q){const ok=btn.dataset.a===q[1];$$(".answer-button").forEach(b=>{b.disabled=true;if(b.dataset.a===q[1])b.classList.add("correct")});if(!ok)btn.classList.add("wrong");if(ok){state.score+=100+state.streak*20;state.correct++;state.streak++;$("#feedbackIcon").textContent="✅";$("#feedbackLabel").textContent="Chính xác"}else{state.streak=0;$("#feedbackIcon").textContent="❓";$("#feedbackLabel").textContent="Chưa đúng"}$("#feedbackTitle").textContent=q[1];$("#feedbackText").textContent=q[3];state.i++;setTimeout(()=>show("feedbackScreen"),350)}
function next(){if(state.i>=state.deck.length)return finish();show("gameScreen");render()}function finish(){const old=Number(localStorage.getItem("quiz-theo-chu-de-best")||0);if(state.score>old)localStorage.setItem("quiz-theo-chu-de-best",state.score);best();$("#resultTitle").textContent=state.correct>=7?"Quiz master rồi đó!":state.correct>=5?"Kiến thức khá chắc!":"Chọn chủ đề khác thử tiếp!";$("#finalScore").textContent=state.score;$("#finalCorrect").textContent=`${state.correct}/${state.deck.length} câu đúng`;if(typeof recordGameScore==='function'){recordGameScore('Quiz Theo Chủ Đề',state.score,'❓');}show("resultScreen")}
async function share(text,msg){const url=location.origin+location.pathname;if(navigator.share){try{await navigator.share({title:"Quiz theo chủ đề",text,url});return}catch(e){if(e.name==="AbortError")return}}await navigator.clipboard.writeText(`${text} ${url}`);toast(msg)}
$("#startButton").onclick=start;$("#replayButton").onclick=start;$("#nextButton").onclick=next;$("#shareGameButton").onclick=()=>share("Thử chơi Quiz theo chủ đề: chọn chủ đề và trả lời kiến thức vui.","Đã sao chép link game");$("#welcomeShareButton").onclick=$("#shareGameButton").onclick;$("#shareResultButton").onclick=()=>share(`Tôi được ${state.score} điểm trong Quiz theo chủ đề, đúng ${state.correct}/${state.deck.length} câu.`, "Đã sao chép lời thách");renderTopics();best();
