const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const pairs=[["mặt","trời"],["bóng","đèn"],["cầu","vồng"],["trí","nhớ"],["thời","gian"],["tình","bạn"],["gia","đình"],["học","tập"],["sức","khỏe"],["niềm","tin"],["hy","vọng"],["tự","do"],["bình","yên"],["sáng","tạo"],["kỷ","luật"],["tập","trung"],["kiên","nhẫn"],["can","đảm"],["công","việc"],["du","lịch"],["âm","nhạc"],["thành","công"],["thói","quen"],["mục","tiêu"],["ước","mơ"],["cảm","xúc"],["thiên","nhiên"],["vũ","trụ"],["bài","học"],["câu","chuyện"]];
let st={pairs:[],left:[],right:[],selected:null,done:new Set(),score:0,wrong:0};
function sh(a){const result=[...a];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
function shuffledWithoutSameRow(items,left){for(let attempt=0;attempt<40;attempt++){const result=sh(items);if(result.every((pair,index)=>pair.id!==left[index].id))return result}return [...items.slice(1),items[0]]}
function show(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id))}function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),1800)}function best(){$("#bestScore").textContent=Number(localStorage.getItem("noi-tu-best")||0)}
function start(){st.pairs=sh(pairs).slice(0,8).map((p,i)=>({id:i,l:p[0],r:p[1]}));st.left=sh(st.pairs);st.right=shuffledWithoutSameRow(st.pairs,st.left);st.selected=null;st.done=new Set();st.score=0;st.wrong=0;show("gameScreen");render()}
function render(){$("#pairText").textContent=`${st.done.size}/${st.pairs.length} cặp`;$("#scoreText").textContent=st.score;$("#progressBar").style.width=`${Math.max(5,st.done.size/st.pairs.length*100)}%`;$("#leftCol").innerHTML=st.left.map(p=>`<button class="connect-button ${st.selected===p.id?"selected":""} ${st.done.has(p.id)?"done":""}" data-side="l" data-id="${p.id}">${p.l}</button>`).join("");$("#rightCol").innerHTML=st.right.map(p=>`<button class="connect-button ${st.done.has(p.id)?"done":""}" data-side="r" data-id="${p.id}">${p.r}</button>`).join("");$$(".connect-button").forEach(b=>b.onclick=()=>pick(b.dataset.side,Number(b.dataset.id)));$("#statusText").textContent=st.selected==null?"Chọn từ ở cột trái":"Chọn từ khớp ở cột phải"}
function pick(side,id){if(st.done.has(id))return;if(side==="l"){st.selected=id;return render()}if(st.selected==null)return toast("Chọn cột trái trước");if(st.selected===id){st.done.add(id);st.score+=100;st.selected=null;if(st.done.size===st.pairs.length)return finish();render()}else{st.wrong++;st.score=Math.max(0,st.score-20);toast("Chưa đúng cặp");st.selected=null;render()}}
function finish(){const bonus=Math.max(0,160-st.wrong*20);st.score+=bonus;const old=Number(localStorage.getItem("noi-tu-best")||0);if(st.score>old)localStorage.setItem("noi-tu-best",st.score);best();$("#finalScore").textContent=st.score;$("#finalPairs").textContent=`${st.done.size}/${st.pairs.length} cặp đúng`;if(typeof recordGameScore==='function'){recordGameScore('Nối Từ',st.score,'🔗');}show("resultScreen")}
async function share(text,msg){const url=location.origin+location.pathname;if(navigator.share){try{await navigator.share({title:"Nối từ",text,url});return}catch(e){if(e.name==="AbortError")return}}await navigator.clipboard.writeText(`${text} ${url}`);toast(msg)}
$("#startButton").onclick=start;$("#replayButton").onclick=start;$("#shareGameButton").onclick=()=>share("Thử chơi Nối từ: ghép các cặp từ liên quan thật nhanh.","Đã sao chép link game");$("#welcomeShareButton").onclick=$("#shareGameButton").onclick;$("#shareResultButton").onclick=()=>share(`Tôi được ${st.score} điểm trong Nối từ.`, "Đã sao chép lời thách");best();
