const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const baseData=[["MEMORY","trí nhớ","E",["A","E","I","O"]],["BALANCE","cân bằng","AN",["AN","EN","ON","AL"]],["PROTECT","bảo vệ","OT",["AT","ET","OT","UT"]],["CONNECT","kết nối","NN",["NN","MM","CT","CC"]],["EXPLORE","khám phá","PL",["PR","PL","FL","BR"]],["RESPECT","tôn trọng","SP",["SP","SC","ST","SK"]],["JOURNEY","hành trình","OUR",["OUR","OAR","AIR","EAR"]],["PICTURE","bức tranh","CT",["CH","CK","CT","CR"]],["NATURE","thiên nhiên","TU",["TE","TA","TU","TO"]],["FREEDOM","tự do","EE",["EA","EE","OO","EO"]],["COURAGE","lòng can đảm","AGE",["ACE","AGE","IGE","EGE"]],["SILENCE","sự im lặng","EN",["AN","IN","EN","ON"]],["IMPROVE","cải thiện","PR",["BR","PR","PL","FR"]],["DISCOVER","khám phá ra","COV",["CAV","COV","COR","CON"]],["CREATIVE","sáng tạo","EA",["EA","EE","AI","IA"]],["PATIENT","kiên nhẫn","TI",["CI","TI","DI","LI"]],["WEATHER","thời tiết","TH",["SH","CH","TH","PH"]],["LIBRARY","thư viện","BR",["PR","BL","BR","GR"]],["GARDEN","khu vườn","AR",["OR","ER","AR","IR"]],["FUTURE","tương lai","TU",["TO","TE","TU","TA"]],["HEALTH","sức khỏe","EA",["EA","EE","AI","HE"]],["TEACHER","giáo viên","CH",["SH","CH","TH","GH"]],["VILLAGE","ngôi làng","LL",["LL","LI","LG","GE"]],["WINDOW","cửa sổ","IN",["AN","IN","ON","EN"]]];
function missingPart(word){const len=word.length>=8?3:word.length>=5?2:1;const start=Math.max(0,Math.floor((word.length-len)/2));return word.slice(start,start+len)}
function missingChoices(miss){const letters="ABCDEFGHIJKLMNOPQRSTUVWXYZ";const pool=[miss];while(pool.length<4){let alt="";for(let i=0;i<miss.length;i++)alt+=letters[Math.floor(Math.random()*letters.length)];if(!pool.includes(alt))pool.push(alt)}return pool}
const data=[...new Map([...baseData,...(window.GAME_WORD_BANK_1000||[]).map(w=>{const miss=missingPart(w);return[w,`từ tiếng Anh ${w.length} chữ`,miss,missingChoices(miss)]})].map(item=>[item[0],item])).values()].slice(0,1000);
let st={deck:[],i:0,score:0,correct:0};function sh(a){return[...a].sort(()=>Math.random()-.5)}function show(id){$$(".screen").forEach(x=>x.classList.toggle("active",x.id===id))}function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),2200)}function best(){$("#bestScore").textContent=Number(localStorage.getItem("dien-chu-best")||0)}
function mask(w,miss){const i=w.indexOf(miss);return w.slice(0,i)+"_".repeat(miss.length)+w.slice(i+miss.length)}function spaced(s){return s.split("").join(" ")}
function start(){st={deck:sh(data).slice(0,12),i:0,score:0,correct:0};show("gameScreen");render()}function render(){const [w,vi,miss,choices]=st.deck[st.i];$("#roundText").textContent=`Câu ${st.i+1}/${st.deck.length}`;$("#scoreText").textContent=st.score;$("#progressBar").style.width=`${((st.i+1)/st.deck.length)*100}%`;$("#maskedWord").textContent=spaced(mask(w,miss));$("#hintText").textContent=vi;$("#answerGrid").innerHTML=sh(choices).map(c=>`<button class="answer-button" data-a="${c}">${c}</button>`).join("");$$(".answer-button").forEach(b=>b.onclick=()=>answer(b))}
function answer(btn){const [w,vi,miss]=st.deck[st.i],ok=btn.dataset.a===miss;$$(".answer-button").forEach(b=>{b.disabled=true;if(b.dataset.a===miss)b.classList.add("correct")});if(!ok)btn.classList.add("wrong");if(ok){st.score+=100+w.length*5;st.correct++;$("#feedbackIcon").textContent="✅";$("#feedbackLabel").textContent="Chính xác"}else{$("#feedbackIcon").textContent="📝";$("#feedbackLabel").textContent="Chưa đúng"}$("#feedbackTitle").textContent=w;$("#feedbackText").textContent=`${w} = ${vi}`;st.i++;setTimeout(()=>show("feedbackScreen"),350)}
function next(){if(st.i>=st.deck.length)return finish();show("gameScreen");render()}function finish(){const old=Number(localStorage.getItem("dien-chu-best")||0);if(st.score>old)localStorage.setItem("dien-chu-best",st.score);best();$("#finalScore").textContent=st.score;$("#finalCorrect").textContent=`${st.correct}/${st.deck.length} câu đúng`;if(typeof recordGameScore==='function'){recordGameScore('Điền chữ còn thiếu',st.score,'📝');}show("resultScreen")}
async function share(text,msg){const url=location.origin+location.pathname;if(navigator.share){try{await navigator.share({title:"Điền chữ còn thiếu",text,url});return}catch(e){if(e.name==="AbortError")return}}await navigator.clipboard.writeText(`${text} ${url}`);toast(msg)}
$("#startButton").onclick=start;$("#replayButton").onclick=start;$("#nextButton").onclick=next;$("#shareGameButton").onclick=()=>share("Thử chơi Điền chữ còn thiếu: hoàn thành từ tiếng Anh bị khuyết.","Đã sao chép link game");$("#welcomeShareButton").onclick=$("#shareGameButton").onclick;$("#shareResultButton").onclick=()=>share(`Tôi được ${st.score} điểm trong Điền chữ còn thiếu, đúng ${st.correct}/${st.deck.length} câu.`, "Đã sao chép lời thách");best();
